2025-08-01 21:10:37,337 INFO    MainThread:18476 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-08-01 21:10:37,337 INFO    MainThread:18476 [wandb_setup.py:_flush():80] Configure stats pid to 18476
2025-08-01 21:10:37,337 INFO    MainThread:18476 [wandb_setup.py:_flush():80] Loading settings from C:\Users\AMD\.config\wandb\settings
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_setup.py:_flush():80] Loading settings from C:\Users\AMD\sentinel\desktop-app\wandb\settings
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_init.py:setup_run_log_directory():703] Logging user logs to C:\Users\AMD\sentinel\desktop-app\wandb\run-20250801_211037-78rw0p7q\logs\debug.log
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to C:\Users\AMD\sentinel\desktop-app\wandb\run-20250801_211037-78rw0p7q\logs\debug-internal.log
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_init.py:init():830] calling init triggers
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'system_version': 'v5.0', 'observability_enabled': True, 'weave_integration': True, '_wandb': {}}
2025-08-01 21:10:37,340 INFO    MainThread:18476 [wandb_init.py:init():871] starting backend
2025-08-01 21:10:37,561 INFO    MainThread:18476 [wandb_init.py:init():874] sending inform_init request
2025-08-01 21:10:37,576 INFO    MainThread:18476 [wandb_init.py:init():882] backend started and connected
2025-08-01 21:10:37,578 INFO    MainThread:18476 [wandb_init.py:init():953] updated telemetry
2025-08-01 21:10:37,643 INFO    MainThread:18476 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-08-01 21:10:38,242 INFO    MainThread:18476 [wandb_init.py:init():1029] starting run threads in backend
2025-08-01 21:10:38,677 INFO    MainThread:18476 [wandb_run.py:_console_start():2458] atexit reg
2025-08-01 21:10:38,677 INFO    MainThread:18476 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-08-01 21:10:38,677 INFO    MainThread:18476 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-08-01 21:10:38,677 INFO    MainThread:18476 [wandb_run.py:_redirect():2398] Redirects installed.
2025-08-01 21:10:38,681 INFO    MainThread:18476 [wandb_init.py:init():1075] run started, returning control to user process
2025-08-01 21:28:43,465 INFO    MsgRouterThr:18476 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-08-01 21:28:45,646 ERROR   MainThread:18476 [redirect.py:_on_write():664] [all runs] error in stdout callback
Traceback (most recent call last):
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 2379, in <lambda>
    lambda data: self._console_raw_callback("stdout", data),
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\interface\interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Users\AMD\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\lib\sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
           ^^^^^^^^^^^^^^^^^^^^^
ConnectionAbortedError: [WinError 10053] An established connection was aborted by the software in your host machine
